### ISSUE TITLE
[UIKit] サンプルの一部が正しく再生されない

### ISSUE THREAD

**Issue by koyopro** [gree/lwf-ja#4]
配布されているLWFSとサンプルを手元のMacで変換して、UIKitのサンプルプロジェクト内で再生してみたところ、一部のサンプルが正しく再生されませんでした。
(UIKitは既にサポートされていないのでしょうか？)
### 再生結果
- 01_animated_building.swf: ◯(正しく再生できた)
- 02_animated_building: ◯(正しく再生できた)
- 03_lwf_logo: 画面になにも表示されない
- 04_cat: キャラクターの位置とアニメーションがおかしい
### 利用したLWFSとUIKitのサンプルプロジェクト
- Release 20150210-1258 · gree/lwfs
  https://github.com/gree/lwfs/releases/tag/20150210-1258
- splhack/Hello-LWF-UIKit
  https://github.com/splhack/Hello-LWF-UIKit
### 実行環境

MacOS X (10.9.5)
Xcode6.1.1
iOS7, 8

**Comment by splhack** [comment]
03と04はちょっと特殊でして、

```
* 03_lwf_logo

  飛び跳ねるlwfロゴと対応する.lwfconfファイルです。ロゴはFlashでは
  (0,0)に配置されています。このような配置は後で位置を制御したいlwfを作
  るときによく行われます。これは、しかしながら、変換結果の確認を難しく
  してしまうので、ユーザは.lwfconfファイルによって初期位置を変更するこ
  とができるようになっています。
```

標準状態のHello-LWF-UIKitでは、03は見えない位置に表示されています。LWFS上では、.lwfconfで位置調整されているため見ることができます。

```
* 04_cat

  ActionScriptのコメントとして書かれたJavaScriptを含む例です。猫はスク
  リプトによって水平に移動し、ユーザがボタンをタップするとジャンプしま
  す。この例は、テクスチャシートも使っています。
```

04は、HTML5専用コンテンツとなっています。

**Comment by koyopro** [comment]
コメントありがとうございます。
03, 04ともに不具合ではないことが分かって助かりました。
