### ISSUE TITLE
swf2lwf.rb で ActionScript が無視される

### ISSUE THREAD

**Issue by fum1h1ro** [gree/lwf-ja#5]
http://lwf-users.org/index.php?title=各環境共通のLWFの作り方#.E3.82.A4.E3.83.99.E3.83.B3.E3.83.88.E7.99.BA.E7.94.9F

こちらに従って、swf から `fscommand` でイベントを発生させたいのですが、
コンバートの段階で警告が出てしまい、うまくいきません。

```
WARN: SWF Format Version 25 is not supported
WARN: script not used [damage_24_1]
WARN: script not used [idle_59_1]
WARN: script not used [melee_39_1]
WARN: script not used [move_39_1]
WARN: script not used [turn_7_1]
```

出ている警告は上記のものなのですが、スクリプトそのものがエラーになるのではなく、
そのスクリプトが利用されないようです。

`swf2lwf.rb` を覗いたところ、 `@script_funcname_map` にあって `@using_script_funcname_map` にない場合、上記の警告が出るようです。

最近の Flash CC が古いバージョンの swf を吐けず、もしかしたらその所為かもしれないのですが、何か原因はあるのでしょうか。

**Comment by fum1h1ro** [comment]
`swf2lwf.rb` を追っかけて調べたところ、 `_root` のムービークリップにないスクリプトは無視されてしまうようです。

こちらは仕様となりますか？
特にLWFのドキュメント等には記載が無かったので、確認させてください。

**Comment by splhack** [comment]
- LWFS最新版をインストールしていますか?
- Flash CCでPublish for LWFコマンドを使用していますか?
  - Publish for LWFコマンドはLWFSが自動的にインストールします。
- LWFS上で、思った通りにLWFデータが動作していますか?

swf2lwf.rbを直接使う場合は、-fオプションでflaファイルを指定する必要があります。

**Comment by fum1h1ro** [comment]
`-f` で `.fla` は指定していますが、LWFSは使用していませんでした。
試しにLWFSを利用して `.swf` を出力したところ、正しくイベントが発生するようになりました。
ありがとうございます。

後学のためにお聞きしたいのですが、Publish for LWFは通常のPublishと何が違うのでしょうか。

**Comment by splhack** [comment]
https://github.com/gree/lwf/blob/master/tools/flash/Publish%20for%20LWF.jsfl
コンバートできるようにバージョンを設定したり、名前をつけたり、ビットマップを抽出したりします。
