### ISSUE TITLE
[UIKit] アルファを使ったマスクが効かない

### ISSUE THREAD

**Issue by koyopro** [gree/lwf-ja#7]
UIKitを利用したiOSアプリで、ブレンドモードをアルファに設定したマスク用の画像がそのまま表示されてしまいます。
webkitcss, canvas, webgl での表示は問題ありませんでした。

http://lwf-users.org/index.php?title=Flash%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB#.E3.83.9E.E3.82.B9.E3.82.AF.E3.81.AB.E3.81.A4.E3.81.84.E3.81.A6
こちらの情報以上に注意点などありますか？

よろしくお願い致します。
### 実行環境

MacOS X (10.9.5)
Xcode6.1.1
LWF/UIKit 1.0.6 (podでインストール)
iOS8

**Comment by splhack** [comment]
残念ながら、UIKitレンダラではマスクを使用することはできません。
https://github.com/gree/lwf/wiki/RendererComparison
(将来的にCALayerのmaskで実装されることもあるかもしれませんが未定です)

**Comment by koyopro** [comment]
おぉ残念です。。
ドキュメントページの共有ありがとうございます。
